name: Publish to Maven Central and Docker Hub

on:
  release:
    types: [ published ]

jobs:
  publish:
    environment: mavenCentralPublish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Java
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5
        with:
          cache: gradle
          distribution: temurin
          java-version: |
            11
            21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6
        with:
          cache-disabled: true

      - name: Publish to Maven Central
        run: ./gradlew publishEmbeddedPublicationToMavenCentral
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

      - name: Push To Docker Hub
        run: ./gradlew pushOciImage --registry dockerHub --tag . --tag latest # . is a placeholder for the default tag
        env:
          ORG_GRADLE_PROJECT_dockerHubUsername: ${{ secrets.DOCKER_USERNAME }}
          ORG_GRADLE_PROJECT_dockerHubPassword: ${{ secrets.DOCKER_TOKEN }}

      - name: Attach HiveMQ Zip to GitHub Release
        run: ./gradlew githubRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
