name: Run Snyk monitor on releases

on:
  release:
    types: [ published ]

jobs:
  run-snyk-monitor:
    runs-on: ubuntu-latest
    environment: snyk-monitor-releases

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          path: hivemq-community-edition

      - name: Setup Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
        with:
          distribution: temurin
          java-version: |
            11
            21

      - name: Setup Snyk
        uses: snyk/actions/setup@9adf32b1121593767fc3c057af55b55db032dc04 # v1

      - name: Run Snyk monitor
        run: >
          snyk monitor --configuration-matching=^runtimeClasspath$ --target-reference=${{ github.ref_name }}
          --org=hivemq-releases --project-name=hivemq-community-edition --remote-repo-url=hivemq-community-edition
          --project-lifecycle=production -d hivemq-community-edition
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
